// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGZZsju-AHnokTpkp-zgOBOLpllVGO3so',
    appId: '1:605149454994:web:1fa4eacd5589b306cd7c4b',
    messagingSenderId: '605149454994',
    projectId: 'sleepifyapp',
    authDomain: 'sleepifyapp.firebaseapp.com',
    storageBucket: 'sleepifyapp.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUK5nD3olAHy1t-qSxJHrTN0FAuw8cZ4Y',
    appId: '1:605149454994:android:3a83c6db920084e8cd7c4b',
    messagingSenderId: '605149454994',
    projectId: 'sleepifyapp',
    storageBucket: 'sleepifyapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDewCL49bS7yw623pynhg97A9tHnQIaFV0',
    appId: '1:605149454994:ios:0fe2a4b64728b2d1cd7c4b',
    messagingSenderId: '605149454994',
    projectId: 'sleepifyapp',
    storageBucket: 'sleepifyapp.firebasestorage.app',
    iosBundleId: 'com.example.sleepify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDewCL49bS7yw623pynhg97A9tHnQIaFV0',
    appId: '1:605149454994:ios:0fe2a4b64728b2d1cd7c4b',
    messagingSenderId: '605149454994',
    projectId: 'sleepifyapp',
    storageBucket: 'sleepifyapp.firebasestorage.app',
    iosBundleId: 'com.example.sleepify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDGZZsju-AHnokTpkp-zgOBOLpllVGO3so',
    appId: '1:605149454994:web:a7d2031f174ac0f1cd7c4b',
    messagingSenderId: '605149454994',
    projectId: 'sleepifyapp',
    authDomain: 'sleepifyapp.firebaseapp.com',
    storageBucket: 'sleepifyapp.firebasestorage.app',
  );  
}
